### ISSUE TITLE
recode_rows does not seem to work when Daru::DataFrame is indexed by DateTimeIndex

### ISSUE THREAD

**Issue by Emrys-Merlin** [v0dro/daru#50] opened 2016-02-11 21:04 UTC
Greetings,

I would like to recode a DataFrame indexed by a DateTimeIndex. This produces a 

```ruby
NoMethodError: undefined method `keys' for nil:NilClass
```
error. A minimal example reproducing the error looks as follows:

```ruby
require 'narray'
require 'daru'
include Daru

index = DateTimeIndex.date_range(start: "2016-02-11", periods: 3)
df = DataFrame.new({a: [1,2,3],
  b: [4,5,6]},
  index: index)

df.recode_rows do |row|
  row
end
```

I am using daru-0.1.1 with ruby-2.2.1p85. 
If I am missing any crucial information, I am very sorry. I will provide them as soon as prompted.
Best regards.

**Comment by Deepakkoli93** [comment] 2016-02-13 15:58
Hi, I've been trying to fix this. 
The problem seems to be with `relation_hash` of an index which is not being set in the constructor of `DateTimeIndex`.  But in `recode_rows` method of DataFrame it is required.

**Comment by v0dro** [comment] 2016-02-15 10:32
The problem is that `DateTimeIndex` does not have a custom `dup` method.

**Comment by Deepakkoli93** [comment] 2016-02-18 05:29
Can you assign it to me?

**Comment by v0dro** [comment] 2016-02-19 17:28
Sure!

**Closed** 2016-03-09 07:05 UTC
Labels: bug
